version: "3.4"

services:
  scope-demo-scala:
    build: .
    image: scope/scope-demo-scala
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - JENKINS_URL
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
      - JDK=${JDK}
      - JAVA_PROFILE=${JAVA_PROFILE}
      - GIT_COMMIT=${GIT_COMMIT}
      - IS_CI=${IS_CI}
    volumes:
      - ~/.scope:/root/.scope